# Generated by Django 3.2.4 on 2021-07-08 10:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210621_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=tinymce.models.HTMLField(default='', max_length=5000),
        ),
    ]
