# Generated by Django 3.2.4 on 2021-06-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
                ('rating', models.IntegerField(default=5)),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
    ]
