# Generated by Django 3.2.4 on 2021-06-09 13:56

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Functionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functionality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Suitable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suitable_for', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, max_length=200, null=True)),
                ('thumbnail', models.ImageField(upload_to='platforms/thumbnails')),
                ('suitable_for_text', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Geeignet für Text')),
                ('is_free', models.BooleanField(default=False, verbose_name='Kostenlose variante')),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Startpreis')),
                ('pricing_note', models.CharField(max_length=200, verbose_name='Startpreis für')),
                ('pricing_text', models.TextField(blank=True, null=True)),
                ('price_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('image_detail', models.ImageField(blank=True, null=True, upload_to='platforms/images')),
                ('short_description', models.TextField(blank=True, max_length=50000, null=True)),
                ('who_use_it', models.TextField(blank=True, max_length=50000, null=True)),
                ('when_to_use', models.TextField(blank=True, max_length=50000, null=True)),
                ('link', models.CharField(max_length=50000)),
                ('tutorial', models.TextField(blank=True, max_length=50000, null=True)),
                ('tutorial_video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('design_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('tested', models.BooleanField(default=False)),
                ('test_report', models.TextField(blank=True, max_length=50000, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('functionality', models.ManyToManyField(max_length=200, to='platforms.Functionality', verbose_name='Funktionalitäten')),
                ('suitable_for', models.ManyToManyField(to='platforms.Suitable', verbose_name='Geeignet für')),
            ],
            options={
                'verbose_name_plural': 'Plattformen',
            },
        ),
    ]
