# Generated by Django 3.2.4 on 2021-07-08 10:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='pricing_text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
