# Generated by Django 3.2.4 on 2021-07-08 10:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_alter_platform_pricing_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='test_report',
            field=tinymce.models.HTMLField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='tutorial',
            field=tinymce.models.HTMLField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='when_to_use',
            field=tinymce.models.HTMLField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='who_use_it',
            field=tinymce.models.HTMLField(blank=True, max_length=50000, null=True),
        ),
    ]
