# Generated by Django 3.2.4 on 2021-07-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_auto_20210708_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='interaction_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Interaktionsbewertung'),
        ),
    ]
