# Generated by Django 3.2.4 on 2021-07-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_platform_interaction_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='interaction_rating',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Interaktionsbewertung'),
        ),
    ]
